<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.3 on win32)" generated="20240523 11:09:18.967" rpa="false">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="GetClaimStatus" source="C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\GetClaimStatus.robot">
<test id="s1-s1-t1" name="${Testcase id} ${Type} ${Desc}">
<status status="FAIL" starttime="20240523 11:09:19.382" endtime="20240523 11:09:19.383" critical="yes">Test case contains no keywords.</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20240523 11:09:18.991" endtime="20240523 11:09:19.384"></status>
</suite>
<status status="FAIL" starttime="20240523 11:09:18.975" endtime="20240523 11:09:19.385"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" id="s1-s1" name="GetClaimStatus">Suites.GetClaimStatus</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240523 11:09:19.365" level="ERROR">Error in file 'C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\GetClaimStatus.robot' on line 10: Resource file '..\Resources\Keyword\CliamSub.robot' does not exist.</msg>
<msg timestamp="20240523 11:09:19.379" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\GetClaimStatus.robot", line 0</msg>
<msg timestamp="20240523 11:09:19.379" level="ERROR">In source file:
  File "../Resources/DataDriven/GetClaimStatus.xlsx", line 0</msg>
<msg timestamp="20240523 11:09:19.381" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\../Resources/DataDriven/GetClaimStatus.xlsx but file does not exist.</msg>
</errors>
</robot>
