<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.3 on win32)" generated="20240523 11:09:18.954" rpa="false">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="UpdateIC" source="C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\UpdateIC.robot">
<test id="s1-s1-t1" name="verify update IC">
<tags>
<tag>regression</tag>
<tag>smoke</tag>
</tags>
<status status="FAIL" starttime="20240523 11:09:19.392" endtime="20240523 11:09:19.393" critical="yes">Test case contains no keywords.</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20240523 11:09:18.988" endtime="20240523 11:09:19.395"></status>
</suite>
<status status="FAIL" starttime="20240523 11:09:18.967" endtime="20240523 11:09:19.396"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">regression</stat>
<stat pass="0" fail="1">smoke</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" id="s1-s1" name="UpdateIC">Suites.UpdateIC</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240523 11:09:19.377" level="ERROR">Error in file 'C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\UpdateIC.robot' on line 10: Resource file '..\Resources\Keyword\CliamSub.robot' does not exist.</msg>
<msg timestamp="20240523 11:09:19.390" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\UpdateIC.robot", line 0</msg>
<msg timestamp="20240523 11:09:19.390" level="ERROR">In source file:
  File "../Resources/DataDriven/UpdateIC.xlsx", line 0</msg>
<msg timestamp="20240523 11:09:19.392" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\../Resources/DataDriven/UpdateIC.xlsx but file does not exist.</msg>
</errors>
</robot>
