<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.3 on win32)" generated="20240523 11:09:18.734" rpa="false">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="UpdateIntegratedClaim" source="C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\UpdateIntegratedClaim.robot">
<test id="s1-s1-t1" name="${Testcase id} ${Type} ${Desc}">
<status status="FAIL" starttime="20240523 11:09:19.159" endtime="20240523 11:09:19.161" critical="yes">Test case contains no keywords.</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20240523 11:09:18.767" endtime="20240523 11:09:19.162"></status>
</suite>
<status status="FAIL" starttime="20240523 11:09:18.746" endtime="20240523 11:09:19.163"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" id="s1-s1" name="UpdateIntegratedClaim">Suites.UpdateIntegratedClaim</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240523 11:09:19.147" level="ERROR">Error in file 'C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\UpdateIntegratedClaim.robot' on line 10: Resource file '..\Resources\Keyword\CliamSub.robot' does not exist.</msg>
<msg timestamp="20240523 11:09:19.156" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\UpdateIntegratedClaim.robot", line 0</msg>
<msg timestamp="20240523 11:09:19.156" level="ERROR">In source file:
  File "../Resources/DataDriven/UpdateIntegratedClaim.xlsx", line 0</msg>
<msg timestamp="20240523 11:09:19.158" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\AGebril\PycharmProjects\QC_Automation_Claim\Tests\../Resources/DataDriven/UpdateIntegratedClaim.xlsx but file does not exist.</msg>
</errors>
</robot>
